//! Includes
#include "game.h"


//! Variables


//! Code

orxSTATUS orxFASTCALL Bootstrap()
{
  orxSTATUS eResult = orxSTATUS_SUCCESS;

  // Adds default release config paths or do other stuffs
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, "../../../", orxFALSE);

  // Loads config file
  orxConfig_Load("Game.ini");

  // Done!
  return eResult;
}

orxSTATUS orxFASTCALL Init()
{
  orxSTATUS eResult = orxSTATUS_SUCCESS;

  // Creates viewport
  orxViewport_CreateFromConfig("Viewport");

  // Creates scene
  orxObject_CreateFromConfig("Scene");

  // Done!
  return eResult;
}

orxSTATUS orxFASTCALL Run()
{
  orxVECTOR vMousePos;
  orxSTATUS eResult = orxSTATUS_SUCCESS;

  // Gets mouse world position
  if(orxRender_GetWorldPosition(orxMouse_GetPosition(&vMousePos), orxNULL, &vMousePos))
  {
    // Has Action input just been triggered?
    if(orxInput_IsActive("Action") && orxInput_HasNewStatus("Action"))
    {
      orxOBJECT *pstObject;

      // Updates position (to push it in the middle of the camera frustum)
      vMousePos.fZ += orxFLOAT_1;

      // Pushes the "Test" config section
      orxConfig_PushSection("Test");

      // Creates an object, whose name was selected from the RandomList, that uses a sprite from the spritesheet generated by TexturePacker
      pstObject = orxObject_CreateFromConfig(orxConfig_GetString("RandomList"));

      // Pops config section
      orxConfig_PopSection();

      // Success?
      if(pstObject)
      {
        // Updates its position
        orxObject_SetPosition(pstObject, &vMousePos);
      }
    }
  }
  // Screenshot?
  if(orxInput_IsActive("Screenshot") && orxInput_HasNewStatus("Screenshot"))
  {
    // Captures it
    orxScreenshot_Capture();
  }
  // Quitting?
  if(orxInput_IsActive("Quit"))
  {
    // Updates result
    eResult = orxSTATUS_FAILURE;
  }

  // Done!
  return eResult;
}

void orxFASTCALL Exit()
{
  // We could delete everything we created here but orx will do it for us anyway =)
}

int main(int argc, char **argv)
{

  orxConfig_SetBootstrap(Bootstrap);

  // Executes orx
  orx_Execute(argc, argv, Init, Run, Exit);

  // Done!
  return EXIT_SUCCESS;
}


#ifdef __orxWINDOWS__

#include "windows.h"

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{

  orxConfig_SetBootstrap(Bootstrap);

  // Executes orx
  orx_WinExecute(Init, Run, Exit);

  // Done!
  return EXIT_SUCCESS;
}

#endif // __orxWINDOWS__
